---
output: 
    html_document:
        theme: null
        highlight: null
        mathjax: null
---

<div class="jumbotron">
  <h2>Beysian network for prediction of biochar performance</h2>
<p>In this project we use the bayesian network to understand the interconnection between different soil, biochar and management properties with the aim of predicting the probable response of biochar on crop growth.<p>

</div>





## Biochar
<blockquote>
Biochar is charcoal used as a soil amendment. Like most charcoal, biochar is made from biomass via pyrolysis. Biochar is under investigation as an approach to carbon sequestration to produce negative carbon dioxide emissions. Biochar thus has the potential to help mitigate climate change via carbon sequestration.
  <small>Wikipedia</small>
</blockquote>
<p><a class="btn btn-primary btn">Learn more</a></p>

## Bayesian Network (BN)
<blockquote>

<p>A Bayesian network, Bayes network, belief network, Bayes(ian) model or probabilistic directed acyclic graphical model is a probabilistic graphical model (a type of statistical model) that represents a set of random variables and their conditional dependencies via a directed acyclic graph (DAG). For example, a Bayesian network could represent the probabilistic relationships between diseases and symptoms. Given symptoms, the network can be used to compute the probabilities of the presence of various diseases.</p>
  <small>Wikipedia</small>
</blockquote>
<p><a class="btn btn-primary btn">Learn more</a></p>





  <div class="well">
  Design and developed by Hamze Dokoohaki - hamzed@iastate.edu
  </div>